'''
FPL BigQuery Schemas
Derived from the FPL bootstrap-static API response.
'''

from google.cloud import bigquery

F = bigquery.SchemaField

FIXTURES_SCHEMA = [
    F("code",                       "INTEGER",  "NULLABLE"),
    F("event",                      "INTEGER",  "NULLABLE"),
    F("finished",                   "BOOLEAN",  "NULLABLE"),
    F("finished_provisional",       "BOOLEAN",  "NULLABLE"),
    F("id",                         "INTEGER",  "NULLABLE"),
    F("kickoff_time",               "STRING",   "NULLABLE"),
    F("minutes",                    "INTEGER",  "NULLABLE"),
    F("provisional_start_time",     "BOOLEAN",  "NULLABLE"),
    F("started",                    "BOOLEAN",  "NULLABLE"),
    F("team_a",                     "INTEGER",  "NULLABLE"),
    F("team_a_score",               "INTEGER",  "NULLABLE"),
    F("team_h",                     "INTEGER",  "NULLABLE"),
    F("team_h_score",               "INTEGER",  "NULLABLE"),
    F("team_h_difficulty",          "INTEGER",  "NULLABLE"),
    F("team_a_difficulty",          "INTEGER",  "NULLABLE"),
    F("pulse_id",                   "INTEGER",  "NULLABLE"),
    F("stats", "RECORD", "REPEATED", fields=[
        F("identifier", "STRING", "NULLABLE"),
        F("a", "RECORD", "REPEATED", fields=[
            F("value",   "INTEGER", "NULLABLE"),
            F("element", "INTEGER", "NULLABLE"),
        ]),
        F("h", "RECORD", "REPEATED", fields=[
            F("value",   "INTEGER", "NULLABLE"),
            F("element", "INTEGER", "NULLABLE"),
        ]),
    ]),
    F("ingestion_timestamp",        "STRING",   "NULLABLE"),
]

PLAYERS_SCHEMA = [
    F("can_transact",                       "BOOLEAN",   "NULLABLE"),
    F("can_select",                         "BOOLEAN",   "NULLABLE"),
    F("chance_of_playing_next_round",       "FLOAT",     "NULLABLE"),
    F("chance_of_playing_this_round",       "FLOAT",     "NULLABLE"),
    F("code",                               "INTEGER",   "NULLABLE"),
    F("cost_change_event",                  "INTEGER",   "NULLABLE"),
    F("cost_change_event_fall",             "INTEGER",   "NULLABLE"),
    F("cost_change_start",                  "INTEGER",   "NULLABLE"),
    F("cost_change_start_fall",             "INTEGER",   "NULLABLE"),
    F("price_change_percent",               "STRING",    "NULLABLE"),
    F("dreamteam_count",                    "INTEGER",   "NULLABLE"),
    F("element_type",                       "INTEGER",   "NULLABLE"),
    F("ep_next",                            "STRING",    "NULLABLE"),
    F("ep_this",                            "STRING",    "NULLABLE"),
    F("event_points",                       "INTEGER",   "NULLABLE"),
    F("first_name",                         "STRING",    "NULLABLE"),
    F("form",                               "STRING",    "NULLABLE"),
    F("id",                                 "INTEGER",   "NULLABLE"),
    F("in_dreamteam",                       "BOOLEAN",   "NULLABLE"),
    F("news",                               "STRING",    "NULLABLE"),
    F("news_added",                         "STRING",    "NULLABLE"),
    F("now_cost",                           "INTEGER",   "NULLABLE"),
    F("photo",                              "STRING",    "NULLABLE"),
    F("points_per_game",                    "STRING",    "NULLABLE"),
    F("removed",                            "BOOLEAN",   "NULLABLE"),
    F("second_name",                        "STRING",    "NULLABLE"),
    F("selected_by_percent",               "STRING",    "NULLABLE"),
    F("special",                            "BOOLEAN",   "NULLABLE"),
    F("squad_number",                       "INTEGER",   "NULLABLE"),
    F("status",                             "STRING",    "NULLABLE"),
    F("team",                               "INTEGER",   "NULLABLE"),
    F("team_code",                          "INTEGER",   "NULLABLE"),
    F("total_points",                       "INTEGER",   "NULLABLE"),
    F("transfers_in",                       "INTEGER",   "NULLABLE"),
    F("transfers_in_event",                 "INTEGER",   "NULLABLE"),
    F("transfers_out",                      "INTEGER",   "NULLABLE"),
    F("transfers_out_event",                "INTEGER",   "NULLABLE"),
    F("value_form",                         "STRING",    "NULLABLE"),
    F("value_season",                       "STRING",    "NULLABLE"),
    F("web_name",                           "STRING",    "NULLABLE"),
    F("known_name",                         "STRING",    "NULLABLE"),
    F("region",                             "INTEGER",   "NULLABLE"),
    F("team_join_date",                     "STRING",    "NULLABLE"),
    F("birth_date",                         "STRING",    "NULLABLE"),
    F("has_temporary_code",                 "BOOLEAN",   "NULLABLE"),
    F("opta_code",                          "STRING",    "NULLABLE"),
    F("minutes",                            "INTEGER",   "NULLABLE"),
    F("goals_scored",                       "INTEGER",   "NULLABLE"),
    F("assists",                            "INTEGER",   "NULLABLE"),
    F("clean_sheets",                       "INTEGER",   "NULLABLE"),
    F("goals_conceded",                     "INTEGER",   "NULLABLE"),
    F("own_goals",                          "INTEGER",   "NULLABLE"),
    F("penalties_saved",                    "INTEGER",   "NULLABLE"),
    F("penalties_missed",                   "INTEGER",   "NULLABLE"),
    F("yellow_cards",                       "INTEGER",   "NULLABLE"),
    F("red_cards",                          "INTEGER",   "NULLABLE"),
    F("saves",                              "INTEGER",   "NULLABLE"),
    F("bonus",                              "INTEGER",   "NULLABLE"),
    F("bps",                                "INTEGER",   "NULLABLE"),
    F("influence",                          "STRING",    "NULLABLE"),
    F("creativity",                         "STRING",    "NULLABLE"),
    F("threat",                             "STRING",    "NULLABLE"),
    F("ict_index",                          "STRING",    "NULLABLE"),
    F("clearances_blocks_interceptions",    "INTEGER",   "NULLABLE"),
    F("recoveries",                         "INTEGER",   "NULLABLE"),
    F("tackles",                            "INTEGER",   "NULLABLE"),
    F("defensive_contribution",             "INTEGER",   "NULLABLE"),
    F("starts",                             "INTEGER",   "NULLABLE"),
    F("expected_goals",                     "STRING",    "NULLABLE"),
    F("expected_assists",                   "STRING",    "NULLABLE"),
    F("expected_goal_involvements",         "STRING",    "NULLABLE"),
    F("expected_goals_conceded",            "STRING",    "NULLABLE"),
    F("corners_and_indirect_freekicks_order", "INTEGER", "NULLABLE"),
    F("corners_and_indirect_freekicks_text",  "STRING",  "NULLABLE"),
    F("direct_freekicks_order",             "INTEGER",   "NULLABLE"),
    F("direct_freekicks_text",              "STRING",    "NULLABLE"),
    F("penalties_order",                    "INTEGER",   "NULLABLE"),
    F("penalties_text",                     "STRING",    "NULLABLE"),
    F("scout_risks", "RECORD", "REPEATED", fields=[
        F("property", "STRING",  "NULLABLE"),
        F("notes",    "STRING",  "NULLABLE"),
        F("gameweek", "INTEGER", "NULLABLE"),
        F("url",      "STRING",  "NULLABLE"),
    ]),
    F("scout_news_link",                    "STRING",    "NULLABLE"),
    F("influence_rank",                     "INTEGER",   "NULLABLE"),
    F("influence_rank_type",                "INTEGER",   "NULLABLE"),
    F("creativity_rank",                    "INTEGER",   "NULLABLE"),
    F("creativity_rank_type",               "INTEGER",   "NULLABLE"),
    F("threat_rank",                        "INTEGER",   "NULLABLE"),
    F("threat_rank_type",                   "INTEGER",   "NULLABLE"),
    F("ict_index_rank",                     "INTEGER",   "NULLABLE"),
    F("ict_index_rank_type",                "INTEGER",   "NULLABLE"),
    F("expected_goals_per_90",              "FLOAT",     "NULLABLE"),
    F("saves_per_90",                       "FLOAT",     "NULLABLE"),
    F("expected_assists_per_90",            "FLOAT",     "NULLABLE"),
    F("expected_goal_involvements_per_90",  "FLOAT",     "NULLABLE"),
    F("expected_goals_conceded_per_90",     "FLOAT",     "NULLABLE"),
    F("goals_conceded_per_90",              "FLOAT",     "NULLABLE"),
    F("now_cost_rank",                      "INTEGER",   "NULLABLE"),
    F("now_cost_rank_type",                 "INTEGER",   "NULLABLE"),
    F("form_rank",                          "INTEGER",   "NULLABLE"),
    F("form_rank_type",                     "INTEGER",   "NULLABLE"),
    F("points_per_game_rank",               "INTEGER",   "NULLABLE"),
    F("points_per_game_rank_type",          "INTEGER",   "NULLABLE"),
    F("selected_rank",                      "INTEGER",   "NULLABLE"),
    F("selected_rank_type",                 "INTEGER",   "NULLABLE"),
    F("starts_per_90",                      "FLOAT",     "NULLABLE"),
    F("clean_sheets_per_90",               "FLOAT",     "NULLABLE"),
    F("defensive_contribution_per_90",      "FLOAT",     "NULLABLE"),
    F("ingestion_timestamp",               "STRING",    "NULLABLE"),
]

TEAMS_SCHEMA = [
    F("code",                    "INTEGER",  "NULLABLE"),
    F("draw",                    "INTEGER",  "NULLABLE"),
    F("form",                    "STRING",   "NULLABLE"),
    F("id",                      "INTEGER",  "NULLABLE"),
    F("loss",                    "INTEGER",  "NULLABLE"),
    F("name",                    "STRING",   "NULLABLE"),
    F("played",                  "INTEGER",  "NULLABLE"),
    F("points",                  "INTEGER",  "NULLABLE"),
    F("position",                "INTEGER",  "NULLABLE"),
    F("short_name",              "STRING",   "NULLABLE"),
    F("strength",                "INTEGER",  "NULLABLE"),
    F("team_division",           "STRING",   "NULLABLE"),
    F("unavailable",             "BOOLEAN",  "NULLABLE"),
    F("win",                     "INTEGER",  "NULLABLE"),
    F("strength_overall_home",   "INTEGER",  "NULLABLE"),
    F("strength_overall_away",   "INTEGER",  "NULLABLE"),
    F("strength_attack_home",    "INTEGER",  "NULLABLE"),
    F("strength_attack_away",    "INTEGER",  "NULLABLE"),
    F("strength_defence_home",   "INTEGER",  "NULLABLE"),
    F("strength_defence_away",   "INTEGER",  "NULLABLE"),
    F("pulse_id",                "INTEGER",  "NULLABLE"),
    F("ingestion_timestamp",     "STRING",   "NULLABLE"),
]

MATCHES_SCHEMA = [
    F("id",                       "INTEGER",  "NULLABLE"),
    F("name",                     "STRING",   "NULLABLE"),
    F("deadline_time",            "STRING",   "NULLABLE"),
    F("release_time",             "STRING",   "NULLABLE"),
    F("average_entry_score",      "INTEGER",  "NULLABLE"),
    F("finished",                 "BOOLEAN",  "NULLABLE"),
    F("data_checked",             "BOOLEAN",  "NULLABLE"),
    F("highest_scoring_entry",    "INTEGER",  "NULLABLE"),
    F("deadline_time_epoch",      "INTEGER",  "NULLABLE"),
    F("deadline_time_game_offset","INTEGER",  "NULLABLE"),
    F("highest_score",            "INTEGER",  "NULLABLE"),
    F("is_previous",              "BOOLEAN",  "NULLABLE"),
    F("is_current",               "BOOLEAN",  "NULLABLE"),
    F("is_next",                  "BOOLEAN",  "NULLABLE"),
    F("cup_leagues_created",      "BOOLEAN",  "NULLABLE"),
    F("h2h_ko_matches_created",   "BOOLEAN",  "NULLABLE"),
    F("can_enter",                "BOOLEAN",  "NULLABLE"),
    F("can_manage",               "BOOLEAN",  "NULLABLE"),
    F("released",                 "BOOLEAN",  "NULLABLE"),
    F("ranked_count",             "INTEGER",  "NULLABLE"),
    F("overrides", "RECORD", "NULLABLE", fields=[
        F("pick_multiplier", "STRING",  "NULLABLE"),
        F("rules",           "STRING",  "NULLABLE"),  # JSON string
        F("scoring",         "STRING",  "NULLABLE"),  # JSON string
        F("element_types",   "STRING",  "NULLABLE"),  # JSON string
    ]),
    F("chip_plays", "RECORD", "REPEATED", fields=[
        F("chip_name",            "STRING",   "NULLABLE"),
        F("num_played",           "INTEGER",  "NULLABLE"),
    ]),
    F("most_selected",            "INTEGER",  "NULLABLE"),
    F("most_transferred_in",      "INTEGER",  "NULLABLE"),
    F("top_element",              "INTEGER",  "NULLABLE"),
    F("top_element_info", "RECORD", "NULLABLE", fields=[
        F("id",                   "INTEGER",  "NULLABLE"),
        F("points",               "INTEGER",  "NULLABLE"),
    ]),
    F("transfers_made",           "INTEGER",  "NULLABLE"),
    F("most_captained",           "INTEGER",  "NULLABLE"),
    F("most_vice_captained",      "INTEGER",  "NULLABLE"),
    F("ingestion_timestamp",      "STRING",   "NULLABLE"),
]

PLAYER_TYPES_SCHEMA = [
    F("id",                    "INTEGER",  "NULLABLE"),
    F("plural_name",           "STRING",   "NULLABLE"),
    F("plural_name_short",     "STRING",   "NULLABLE"),
    F("singular_name",         "STRING",   "NULLABLE"),
    F("singular_name_short",   "STRING",   "NULLABLE"),
    F("squad_select",          "INTEGER",  "NULLABLE"),
    F("squad_min_select",      "INTEGER",  "NULLABLE"),
    F("squad_max_select",      "INTEGER",  "NULLABLE"),
    F("squad_min_play",        "INTEGER",  "NULLABLE"),
    F("squad_max_play",        "INTEGER",  "NULLABLE"),
    F("ui_shirt_specific",     "BOOLEAN",  "NULLABLE"),
    F("sub_positions_locked",  "INTEGER",  "REPEATED"),
    F("element_count",         "INTEGER",  "NULLABLE"),
    F("ingestion_timestamp",   "STRING",   "NULLABLE"),
]

PLAYER_HISTORY_SCHEMA = [
    bigquery.SchemaField("element",                          "INTEGER"),
    bigquery.SchemaField("fixture",                          "INTEGER"),
    bigquery.SchemaField("opponent_team",                    "INTEGER"),
    bigquery.SchemaField("total_points",                     "INTEGER"),
    bigquery.SchemaField("was_home",                         "BOOLEAN"),
    bigquery.SchemaField("kickoff_time",                     "STRING"),
    bigquery.SchemaField("team_h_score",                     "INTEGER"),
    bigquery.SchemaField("team_a_score",                     "INTEGER"),
    bigquery.SchemaField("round",                            "INTEGER"),
    bigquery.SchemaField("modified",                         "BOOLEAN"),
    bigquery.SchemaField("minutes",                          "INTEGER"),
    bigquery.SchemaField("goals_scored",                     "INTEGER"),
    bigquery.SchemaField("assists",                          "INTEGER"),
    bigquery.SchemaField("clean_sheets",                     "INTEGER"),
    bigquery.SchemaField("goals_conceded",                   "INTEGER"),
    bigquery.SchemaField("own_goals",                        "INTEGER"),
    bigquery.SchemaField("penalties_saved",                  "INTEGER"),
    bigquery.SchemaField("penalties_missed",                 "INTEGER"),
    bigquery.SchemaField("yellow_cards",                     "INTEGER"),
    bigquery.SchemaField("red_cards",                        "INTEGER"),
    bigquery.SchemaField("saves",                            "INTEGER"),
    bigquery.SchemaField("bonus",                            "INTEGER"),
    bigquery.SchemaField("bps",                              "INTEGER"),
    bigquery.SchemaField("influence",                        "STRING"),
    bigquery.SchemaField("creativity",                       "STRING"),
    bigquery.SchemaField("threat",                           "STRING"),
    bigquery.SchemaField("ict_index",                        "STRING"),
    bigquery.SchemaField("clearances_blocks_interceptions",  "INTEGER"),
    bigquery.SchemaField("recoveries",                       "INTEGER"),
    bigquery.SchemaField("tackles",                          "INTEGER"),
    bigquery.SchemaField("defensive_contribution",           "INTEGER"),
    bigquery.SchemaField("starts",                           "INTEGER"),
    bigquery.SchemaField("expected_goals",                   "STRING"),
    bigquery.SchemaField("expected_assists",                 "STRING"),
    bigquery.SchemaField("expected_goal_involvements",       "STRING"),
    bigquery.SchemaField("expected_goals_conceded",          "STRING"),
    bigquery.SchemaField("value",                            "INTEGER"),
    bigquery.SchemaField("transfers_balance",                "INTEGER"),
    bigquery.SchemaField("selected",                         "INTEGER"),
    bigquery.SchemaField("transfers_in",                     "INTEGER"),
    bigquery.SchemaField("transfers_out",                    "INTEGER"),
    bigquery.SchemaField("player_id",                        "INTEGER"),
    bigquery.SchemaField("ingestion_timestamp",              "STRING"),
]

SCHEMAS = {
    "players":      PLAYERS_SCHEMA,
    "teams":        TEAMS_SCHEMA,
    "matches":      MATCHES_SCHEMA,
    "player_types": PLAYER_TYPES_SCHEMA,
    "fixtures":     FIXTURES_SCHEMA, 
    "player_history": PLAYER_HISTORY_SCHEMA
}